## Anand International College of Engineering Subject 
## Data Science with AI&MLops 
## Date : 16/06/2026 
## Topic – NumPy   
## Assignment 4: 

In [204]:
import numpy as np


1.  Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and print: ○ The first row ○ The last column ○ The diagonal elements A

In [205]:
matrix = np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [206]:
print(matrix[0])
print(matrix[:,-1])
print(np.diag(matrix))


[0 1 2 3 4]
[ 4  9 14 19 24]
[ 0  6 12 18 24]


2. Create two 3 × 3 matrices and perform matrix addition, subtraction, and matrix multiplication. 

In [207]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [208]:
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a + b = [ 0  2  4  6  8 10 12 14 16 18]
a - b = [0 0 0 0 0 0 0 0 0 0]
a * b = [ 0  1  4  9 16 25 36 49 64 81]


3. Create a NumPy array of numbers from 1 to 100 and print all numbers divisible by 3 using Boolean indexing. 

In [209]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [210]:
division = arr[arr%3==0]
division

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

4. Create a 4 × 4 matrix and replace all even numbers with 0. 

In [211]:
matrix_even = np.arange(1,16)
print(matrix_even)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [212]:
matrix_even[matrix_even%2 ==0] = 0
matrix_even

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

5. Create a 5 × 5 matrix of random integers and find: 
○ Maximum value 
○ Minimum value 
○ Mean 
○ Median 

In [213]:
matrix= np.arange(0,26)
print(matrix)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


In [214]:
#maximum value
max_value = np.max(matrix)
print(max_value)

#minimum value
min_value = np.min(matrix)
print("minimum value",min_value)

#Find mean
mean_value = np.mean(matrix)
print("mean value",mean_value)

#median
median_value = np.median(matrix)
print("median value",median_value)

25
minimum value 0
mean value 12.5
median value 12.5


6. Create a NumPy array containing 20 random numbers and sort it in ascending and descending order. 

In [215]:
arr = np.random.randint(1,101,20)  #randint() is used to generate a random integer within a specified range.
print(arr)

[14 29 80 51 51 63 27 83 95 97 64 87 35 78 72 59 47 77 70 80]


In [216]:
ascending = np.sort(arr)   #used to arrange the elements 
print(ascending)

descending = np.sort(arr)[::-1]
print(descending)

[14 27 29 35 47 51 51 59 63 64 70 72 77 78 80 80 83 87 95 97]
[97 95 87 83 80 80 78 77 72 70 64 63 59 51 51 47 35 29 27 14]


7. Create a 6 × 6 matrix and print: 
○ Main diagonal 
○ Upper triangular part 
○ Lower triangular part

In [217]:
matrix = np.arange(1,37).reshape(6,6)
print(matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [218]:
print(np.diag(matrix))

[ 1  8 15 22 29 36]


In [219]:
print(np.triu(matrix))


[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]


In [220]:
print(np.tril(matrix))

[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


8. Create a NumPy array of 20 elements and reshape it into: 
○ 4 × 5 matrix 
○ 2 × 10 matrix 
○ 5 × 4 matrix 

In [221]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [222]:
arr = np.arange(20).reshape(4,5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [223]:
arr = np.arange(20).reshape(2,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [224]:
arr = np.arange(20).reshape(5,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


9. Create a 5 × 5 matrix and calculate the sum of: 
○ Each row 
○ Each column 

In [225]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [226]:
row_sum = np.sum(matrix, axis=1)
print("row is:---",row_sum)

col_sum = np.sum(matrix, axis=0)
print("column is :----",col_sum)

row is:--- [ 21  57  93 129 165 201]
column is :---- [ 96 102 108 114 120 126]


10. Create two arrays and find all common elements between them. 

In [227]:
arr1 = np.array([1,2,3,4,5,6,7])
# print(arr)

arr2 = np.array([2,34,5,3,9,4,1])
# print(arr1)

common = np.intersect1d(arr1,arr2)

print("Common elements:", common)


Common elements: [1 2 3 4 5]


11. Create a 5 × 5 matrix and find the position (row and column index) of the largest element. 

In [228]:
matrix = np.random.randint(1, 100, (5, 5))
print(matrix)

position = np.unravel_index(np.argmax(matrix), matrix.shape)

print("Largest Element:", matrix[position])
print("Row Index:", position[0])
print("Column Index:", position[1])

[[33 91 11 53 35]
 [35 60 73 43 65]
 [87 16  7 33 46]
 [95  5 90  3 79]
 [86  6 80 63 72]]
Largest Element: 95
Row Index: 3
Column Index: 0


12. Create a dataset of students' marks using a NumPy array and find: ● Highest marks ● Lowest marks ● Average marks ● Students scoring above average 

In [230]:
marks = np.array([1,2,3,4,5,6,7,8,9,10])
print(marks)


highest = np.max(marks)
# print(highest)
lowest = np.min(marks)
# print(lowest)
average = np.mean(marks)
# print(average)


average = marks[marks>average]
# print(average)



print("\nHighest marks:", highest)
print("Lowest marks:", lowest)
print("Average marks:", average)
print("Students Scoring above average:",average)

[ 1  2  3  4  5  6  7  8  9 10]

Highest marks: 10
Lowest marks: 1
Average marks: [ 6  7  8  9 10]
Students Scoring above average: [ 6  7  8  9 10]
