In [54]:
import numpy as np


In [2]:
print("/////////////list convert in array////////////")
lst = [1,2,3,4,5,6,7,8,9]
print("This is my list:--",lst)
print("Type of lst:-",type(lst))
print("list convert in array///////")


/////////////list convert in array////////////
This is my list:-- [1, 2, 3, 4, 5, 6, 7, 8, 9]
Type of lst:- <class 'list'>
list convert in array///////


In [3]:
lst = list(range(50))

In [7]:
lst = np.arange(60)
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [6]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((5,10))
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.ones((12,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# arr = np.arange(60)
# arr

In [39]:
arr = np.arange(60)
arr
arr = arr.reshape(12,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [40]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print(arr.dtype)
print(arr.ndim)

shape of array (12, 5)
size of array 60
int64
2


In [46]:
arr[0,]

array([0, 1, 2, 3, 4])

In [45]:
arr[-1,-1]

np.int64(59)

In [44]:
arr[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [71]:
arr = np.arange(255)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [72]:
arr = arr.reshape((5,3,17))
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33],
        [ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
          63,  64,  65,  66,  67],
        [ 68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
          80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101]],

       [[102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152]],

       [[153, 154, 155, 156, 157, 158, 159, 160, 161, 162,

In [73]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print(arr.dtype)
print(arr.ndim)

shape of array (5, 3, 17)
size of array 255
int64
3


In [74]:
arr[4]

array([[204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
        217, 218, 219, 220],
       [221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236, 237],
       [238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
        251, 252, 253, 254]])

In [75]:
arr[0:,0:1,0:1]

array([[[  0]],

       [[ 51]],

       [[102]],

       [[153]],

       [[204]]])

In [80]:
arr[0:,0:3,0:3]

array([[[  0,   1,   2],
        [ 17,  18,  19],
        [ 34,  35,  36]],

       [[ 51,  52,  53],
        [ 68,  69,  70],
        [ 85,  86,  87]],

       [[102, 103, 104],
        [119, 120, 121],
        [136, 137, 138]],

       [[153, 154, 155],
        [170, 171, 172],
        [187, 188, 189]],

       [[204, 205, 206],
        [221, 222, 223],
        [238, 239, 240]]])

In [81]:
arr.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [82]:
arr.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [86]:
np.random.randint(1,10,5)

array([9, 9, 5, 1, 4])

In [84]:
np.random.random((10,5))

array([[0.76304355, 0.05517157, 0.17158356, 0.79261882, 0.05311556],
       [0.21892924, 0.33019054, 0.96633212, 0.39590507, 0.07896277],
       [0.49474388, 0.17880407, 0.05862244, 0.11052952, 0.14674359],
       [0.16710283, 0.56201826, 0.1861102 , 0.63678315, 0.8903198 ],
       [0.62569052, 0.75151148, 0.81848426, 0.49756303, 0.09003407],
       [0.73440399, 0.08892775, 0.89409679, 0.24595538, 0.98514905],
       [0.48408239, 0.84173406, 0.16940214, 0.90520468, 0.18284763],
       [0.7082976 , 0.32305078, 0.15103609, 0.75230018, 0.73996276],
       [0.52703701, 0.07178005, 0.2466141 , 0.00399099, 0.19442242],
       [0.45711321, 0.18138113, 0.08430646, 0.21524315, 0.1518047 ]])

In [87]:
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33],
        [ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
          63,  64,  65,  66,  67],
        [ 68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
          80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101]],

       [[102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152]],

       [[153, 154, 155, 156, 157, 158, 159, 160, 161, 162,

In [ ]:
np.random.normal(10)

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.0201005 , 1.04020101, 1.06030151, 1.08040201,
       1.10050251, 1.12060302, 1.14070352, 1.16080402, 1.18090452,
       1.20100503, 1.22110553, 1.24120603, 1.26130653, 1.28140704,
       1.30150754, 1.32160804, 1.34170854, 1.36180905, 1.38190955,
       1.40201005, 1.42211055, 1.44221106, 1.46231156, 1.48241206,
       1.50251256, 1.52261307, 1.54271357, 1.56281407, 1.58291457,
       1.60301508, 1.62311558, 1.64321608, 1.66331658, 1.68341709,
       1.70351759, 1.72361809, 1.74371859, 1.7638191 , 1.7839196 ,
       1.8040201 , 1.8241206 , 1.84422111, 1.86432161, 1.88442211,
       1.90452261, 1.92462312, 1.94472362, 1.96482412, 1.98492462,
       2.00502513, 2.02512563, 2.04522613, 2.06532663, 2.08542714,
       2.10552764, 2.12562814, 2.14572864, 2.16582915, 2.18592965,
       2.20603015, 2.22613065, 2.24623116, 2.26633166, 2.28643216,
       2.30653266, 2.32663317, 2.34673367, 2.36683417, 2.38693467,
       2.40703518, 2.42713568, 2.44723618, 2.46733668, 2.48743

In [ ]:
# arr.reshape(1,3,1)

ValueError: cannot reshape array of size 255 into shape (1,3,1)

In [101]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([3,5,6,2,7,3,5,7])
print("Arithmetic Operators")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a // b =", a // b)
print("a % b = ", a % b)
print("a ** b =", a ** b)

Arithmetic Operators
a + b = [ 4  7  9  6 12  9 12 15]
a - b = [-2 -3 -3  2 -2  3  2  1]
a * b = [ 3 10 18  8 35 18 35 56]
a / b = [0.33333333 0.4        0.5        2.         0.71428571 2.
 1.4        1.14285714]
a // b = [0 0 0 2 0 2 1 1]
a % b =  [1 2 3 0 5 0 2 1]
a ** b = [      1      32     729      16   78125     216   16807 2097152]
