#### Q1. NumPy kya hai?

NumPy Python ki numerical computing library hai jo arrays aur mathematical operations ke liye use hoti hai.

In [56]:
import numpy as np


In [57]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


#### 2. Array Ki Type Dekhna

In [58]:
arr = np.array([1,2,3,4,5,6,7])
print(type(arr))

<class 'numpy.ndarray'>


#### 3. 2D Array

In [59]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 4. Array Properties

In [60]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


#### 5. Indexing

In [61]:
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[2])

10
30


#### 6. Slicing

In [62]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


#### Q4. Shape aur Size mein difference?
shape → rows aur columns batata hai
size → total elements batata hai

In [63]:
print("/////////////list convert in array////////////")
lst = [1,2,3,4,5,6,7,8,9]
print("This is my list:--",lst)
print("Type of lst:-",type(lst))
print("list convert in array///////")


/////////////list convert in array////////////
This is my list:-- [1, 2, 3, 4, 5, 6, 7, 8, 9]
Type of lst:- <class 'list'>
list convert in array///////


In [64]:
lst = list(range(50))

In [65]:
lst = np.arange(60)
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

#### 7. Special Arrays
Zeros

In [66]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
arr = np.zeros((5,10)) #5rows and 10 cloums
arr


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Ones

In [68]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 8. Range Banana

In [69]:
print(np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [70]:
arr = np.arange(60)
arr
arr = arr.reshape(12,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [71]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print(arr.dtype)
print(arr.ndim)

shape of array (12, 5)
size of array 60
int64
2


In [72]:
arr[0,]

array([0, 1, 2, 3, 4])

In [73]:
arr[-1,-1]

np.int64(59)

In [74]:
arr[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [76]:
arr = np.arange(255)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

#### 11. Reshape

In [77]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [86]:
arr = np.arange(255)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [90]:
arr = arr.reshape((5,3,17))
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33],
        [ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
          63,  64,  65,  66,  67],
        [ 68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
          80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101]],

       [[102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152]],

       [[153, 154, 155, 156, 157, 158, 159, 160, 161, 162,

In [91]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print(arr.dtype)
print(arr.ndim)

shape of array (5, 3, 17)
size of array 255
int64
3


In [100]:
# arr[0]
arr[1]
arr[4]

array([[204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
        217, 218, 219, 220],
       [221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236, 237],
       [238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
        251, 252, 253, 254]])

In [ ]:
arr[0:,0:1,0:1]   #3D array banne k liye ....

array([[[  0]],

       [[ 51]],

       [[102]],

       [[153]],

       [[204]]])

In [101]:
arr[0:,0:3,0:3]  ##3D array banne k liye ....

array([[[  0,   1,   2],
        [ 17,  18,  19],
        [ 34,  35,  36]],

       [[ 51,  52,  53],
        [ 68,  69,  70],
        [ 85,  86,  87]],

       [[102, 103, 104],
        [119, 120, 121],
        [136, 137, 138]],

       [[153, 154, 155],
        [170, 171, 172],
        [187, 188, 189]],

       [[204, 205, 206],
        [221, 222, 223],
        [238, 239, 240]]])

In [ ]:
arr.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
np.random.randint(1,10,5)

array([8, 3, 6, 8, 5])

In [ ]:
np.random.random((10,5))

array([[0.72285276, 0.92984518, 0.72266549, 0.43762304, 0.1421724 ],
       [0.77042759, 0.14802956, 0.60477488, 0.32662688, 0.95807471],
       [0.53908364, 0.21727834, 0.87512221, 0.86096472, 0.9104831 ],
       [0.0697562 , 0.07108222, 0.87530324, 0.39452768, 0.53133145],
       [0.94443039, 0.45478074, 0.23603932, 0.66031305, 0.52343378],
       [0.36153312, 0.64074529, 0.01748003, 0.26037756, 0.63761902],
       [0.47898193, 0.9236094 , 0.91722166, 0.74780943, 0.43075105],
       [0.60973527, 0.29720956, 0.16223561, 0.29390387, 0.88158079],
       [0.37022516, 0.27235324, 0.45347025, 0.86394541, 0.11444865],
       [0.1954521 , 0.6508713 , 0.70821104, 0.81931394, 0.71969484]])

In [ ]:
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16],
        [ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33],
        [ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
          46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
          63,  64,  65,  66,  67],
        [ 68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
          80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101]],

       [[102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152]],

       [[153, 154, 155, 156, 157, 158, 159, 160, 161, 162,

### flatten(): Multidimensional array ko 1D array mein convert karta hai aur uski copy return karta hai.
### ravel(): Multidimensional array ko 1D array mein convert karta hai aur possible ho to original array ka view return karta hai.

In [117]:
arr = np.arange(500)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [124]:
print(arr[-10:])

[490 491 492 493 494 495 496 497 498 499]


In [ ]:
np.random.normal(10)

10.483094413236886

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
# arr.reshape(1,3,1)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([3,5,6,2,7,3,5,7])
print("Arithmetic Operators")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a // b =", a // b)
print("a % b = ", a % b)
print("a ** b =", a ** b)

Arithmetic Operators
a + b = [ 4  7  9  6 12  9 12 15]
a - b = [-2 -3 -3  2 -2  3  2  1]
a * b = [ 3 10 18  8 35 18 35 56]
a / b = [0.33333333 0.4        0.5        2.         0.71428571 2.
 1.4        1.14285714]
a // b = [0 0 0 2 0 2 1 1]
a % b =  [1 2 3 0 5 0 2 1]
a ** b = [      1      32     729      16   78125     216   16807 2097152]
